name: Deploy Caprine to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            if [ ! -d caprine-deploy ]; then
              git clone https://github.com/UbaidSaroya/caprine-deploy.git
            fi
            cd caprine-deploy
            git pull origin main
            npm install
            sudo chown root:root ./node_modules/electron/dist/chrome-sandbox
            sudo chmod 4755 ./node_modules/electron/dist/chrome-sandbox
            nohup xvfb-run npm start > out.log 2>&1 &
          EOF
