name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo apt update -y
          sudo apt install -y nodejs npm git
          cd caprine-deploy || git clone https://github.com/${{ github.repository }}.git caprine-deploy && cd caprine-deploy
          git pull origin main
          npm install
          npm run build || true
          nohup npm start > app.log 2>&1 &
        EOF
