name: Deploy Caprine to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            pkill node || true
            rm -rf ~/caprine-deploy
            git clone https://github.com/UbaidSaroya/caprine-deploy.git
            cd caprine-deploy
            npm install
            nohup xvfb-run npm start > caprine.log 2>&1 &
          EOF

